version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-1

phases:
  install:
    commands:
      - apt update -y
      - apt-get install clamav libnet-dns-perl -y

  pre_build:
    commands:
      - echo Starting build...

  build:
    commands:
      - echo Build started on `date`
      - mkdir -p /tmp/clam
      - perl clamdownloader.pl
      - ls -la /tmp/clam
      - aws s3 sync /tmp/clam s3://<target-bucket>/clam
      - echo Done uploading to S3 `date`
